# The domain used in the home network
domain: local

# The X509 name to use on the certificates
name: {
  country: UK,
  state: Barsetshire,
  locality: Barchester,
  organization: Home Network
}

# A list of hosts to generate certificates for. Each host has a list of names
# and an optional list of IP addresses. The first name in the list is used in
# the output file names
hosts:
  - {names: [unifi, usg, gateway], ip_addresses: [192.168.1.1]}
  - {names: [synology, home-nas], ip_addresses: [192.168.1.2, 10.1.1.2]}
  - {names: [plex, video], ip_addresses: [192.168.1.3]}
  - {names: [home-assistant]}

# The directory to write the certificates to
# This can be overridden on the command line with the --output-directory or -o flag
output_directory: sample_certificates
